# Generated by Django 4.1.4 on 2023-02-04 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carro_compra', '0004_alter_carro_compras_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro_compras',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
