# Generated by Django 4.1.4 on 2023-02-18 00:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0018_alter_electronicomodel_precio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carro_compra', '0005_alter_carro_compras_cantidad'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carro_compras',
            unique_together={('user', 'productos')},
        ),
    ]
