# Generated by Django 4.1.4 on 2023-03-16 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0032_alter_ropamodels_categori'),
        ('carro_compra', '0006_alter_carro_compras_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro_compras',
            name='moda',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ropa_moda_devolver', to='inicio.ropamodels'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carro_compras',
            name='productos',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='carro_devolver', to='inicio.electronicomodel'),
        ),
    ]
