# Generated by Django 4.1.4 on 2023-03-16 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carro_compra', '0007_carro_compras_moda_alter_carro_compras_productos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carro_compras',
            name='moda',
        ),
    ]
