# Generated by Django 4.1.4 on 2023-01-06 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0007_alter_vistas_articulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vistas',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.electronicomodel'),
        ),
    ]
