# Generated by Django 4.1.4 on 2023-01-09 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0009_alter_electronicomodel_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vistas',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devolver_view', to='inicio.electronicomodel'),
        ),
    ]
