# Generated by Django 4.1.4 on 2023-01-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0010_alter_vistas_articulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronicomodel',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
