# Generated by Django 4.1.4 on 2023-01-29 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0011_electronicomodel_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vistas',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devolver_views', to='inicio.electronicomodel'),
        ),
    ]
