# Generated by Django 4.1.4 on 2023-02-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0012_alter_vistas_articulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ofertas_descuentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(max_length=500)),
                ('descuentos', models.IntegerField()),
                ('in_port', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.PositiveIntegerField()),
                ('producto', models.ManyToManyField(to='inicio.electronicomodel')),
            ],
        ),
    ]
