# Generated by Django 4.1.4 on 2023-02-01 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0014_remove_ofertas_descuentos_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertas_descuentos',
            name='descuentos',
            field=models.FloatField(),
        ),
    ]
