# Generated by Django 4.1.4 on 2023-02-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0015_alter_ofertas_descuentos_descuentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronicomodel',
            name='precio',
            field=models.IntegerField(blank=True, max_length=15),
        ),
    ]
