# Generated by Django 4.1.4 on 2023-03-14 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0018_alter_electronicomodel_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electronicomodel',
            name='precio',
        ),
    ]
