# Generated by Django 4.1.4 on 2023-03-14 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0019_remove_electronicomodel_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronicomodel',
            name='precio',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
