# Generated by Django 4.1.4 on 2023-03-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0021_ofertas_descuentos_porciento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertas_descuentos',
            name='porciento',
            field=models.IntegerField(),
        ),
    ]
