# Generated by Django 4.1.4 on 2023-03-15 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0022_alter_ofertas_descuentos_porciento'),
    ]

    operations = [
        migrations.CreateModel(
            name='RopaModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('avatar', models.ImageField(upload_to='')),
                ('size', models.CharField(choices=[('1', 'L'), ('2', 'M'), ('3', 'X'), ('4', 'XL')], max_length=1)),
                ('tipo', models.CharField(choices=[('1', 'abrigo'), ('2', 'pantalon'), ('3', 'tenis')], max_length=1)),
                ('created', models.DateField(auto_now_add=True)),
                ('categori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.categoria')),
            ],
        ),
    ]
