# Generated by Django 4.1.4 on 2023-03-16 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0023_ropamodels'),
    ]

    operations = [
        migrations.AddField(
            model_name='ropamodels',
            name='imagen',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ropamodels',
            name='imagen2',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
  
    ]
