# Generated by Django 4.1.4 on 2023-03-16 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0025_remove_ropamodels_imagen_remove_ropamodels_imagen2'),
    ]

    operations = [
        migrations.AddField(
            model_name='vistas',
            name='imagen',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vistas',
            name='imagen2',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vistas',
            name='imagen3',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
