# Generated by Django 4.1.4 on 2023-03-16 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0026_vistas_imagen_vistas_imagen2_vistas_imagen3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vistas',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='vistas',
            name='imagen2',
        ),
        migrations.RemoveField(
            model_name='vistas',
            name='imagen3',
        ),
        migrations.AddField(
            model_name='ropamodels',
            name='imagen',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ropamodels',
            name='imagen2',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ropamodels',
            name='imagen3',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
