# Generated by Django 4.1.4 on 2023-03-16 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0028_ropamodels_nombre_ropamodels_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ropamodels',
            name='precio',
        ),
    ]
