# Generated by Django 4.1.4 on 2023-03-16 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0032_alter_ropamodels_categori'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ropamodels',
            old_name='categori',
            new_name='categoria',
        ),
    ]
