# Generated by Django 4.1.4 on 2023-03-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0035_electronicomodel_tipo_ropa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronicomodel',
            name='tipo_ropa',
            field=models.CharField(blank=True, choices=[('1', 'abrigo'), ('2', 'pantalon'), ('3', 'tenis'), ('4', 'ropa interior')], max_length=1),
        ),
    ]
